// Generated by scripts/import-writing-question-bank.mjs. Do not edit by hand.
export const GENERATED_WRITING_QUESTIONS = [
  {
    "questionId": "postgrad-en1-2023-writing-a",
    "promptText": "Write a notice to recruit a student for Prof. Smith’s research project on campus sports activities. Specify the duties and requirements of the job.",
    "directions": "Write your answer in about 100 words on the ANSWER SHEET. Do not use your own name in the notice; use “Li Ming” instead. (10 points)",
    "promptKind": "notice",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2023,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2023,
      "sourceFileName": "2023年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "cea9ac7ffb2e6681c96aebb77f59404b4080989ab5d8a3cfa83b33d164c46a84",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "a971ce00912e128674b4a00866d379257702dbc7a248aa2198d1a5f339c70bb0",
    "requiredContentPoints": [
      "specify the duties of the job",
      "specify the requirements of the job"
    ]
  },
  {
    "questionId": "postgrad-en1-2023-writing-b",
    "promptText": "Write an essay based on the picture below. In your essay, you should\n\n1) describe the picture briefly,\n2) interpret the implied meaning, and\n3) give your comments.",
    "directions": "Write your answer in 160–200 words on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2023,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2023-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2023/postgrad-en1-2023-writing-b/prompt.png",
        "alt": "2023 年英语（一）写作题原卷图画",
        "fingerprint": "97d9eeda0be6aa732614d603db649581fe2e8de56d433369ec1a14004a4b0faf"
      }
    ],
    "source": {
      "sourceYear": 2023,
      "sourceFileName": "2023年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "cea9ac7ffb2e6681c96aebb77f59404b4080989ab5d8a3cfa83b33d164c46a84",
      "sourceAssetFingerprint": "97d9eeda0be6aa732614d603db649581fe2e8de56d433369ec1a14004a4b0faf"
    },
    "fingerprint": "e9f2c65e0178bf775a38560c36ed90b4a839ce278003812a09b4a217fb015587",
    "requiredContentPoints": [
      "describe the picture briefly",
      "interpret the implied meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2022-writing-a",
    "promptText": "Write an email to a professor at a British university, inviting him/her to organize a team for the international innovation contest to be held at your university.",
    "directions": "You should write about 100 words on the ANSWER SHEET. Do not use your own name in the email; use “Li Ming” instead. (10 points)",
    "promptKind": "email",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2022,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2022,
      "sourceFileName": "2022年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "2376a5402f0ebb41310edfe23ed1a89237b93c48f2125987bd3aa1b41fd538ea",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "d499a1f9a51ce106b92e1bd1a7ed7273019310e8cee3138cc71e7c674807c718",
    "requiredContentPoints": [
      "invite him/her to organize a team for the international innovation contest to be held at your university"
    ]
  },
  {
    "questionId": "postgrad-en1-2022-writing-b",
    "promptText": "Write an essay of 160–200 words based on the picture below. In your essay, you should\n\n1) describe the picture briefly,\n2) interpret the implied meaning, and\n3) give your comments.",
    "directions": "Write your answer on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2022,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2022-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2022/postgrad-en1-2022-writing-b/prompt.png",
        "alt": "2022 年英语（一）写作题原卷图画",
        "fingerprint": "dc4787a50ac7e119dec4c0a636810c093e85fe8caabd3b3681d35289b4eccd8a"
      }
    ],
    "source": {
      "sourceYear": 2022,
      "sourceFileName": "2022年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "2376a5402f0ebb41310edfe23ed1a89237b93c48f2125987bd3aa1b41fd538ea",
      "sourceAssetFingerprint": "dc4787a50ac7e119dec4c0a636810c093e85fe8caabd3b3681d35289b4eccd8a"
    },
    "fingerprint": "fb38319e665f35fd93aa4ca309fa031cead3d26b55df5c080feff814f5285e37",
    "requiredContentPoints": [
      "describe the picture briefly",
      "interpret the implied meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2021-writing-a",
    "promptText": "A foreign friend of yours has recently graduated from college and intends to find a job in China. Write him/her an e-mail to make some suggestions.",
    "directions": "You should write about 100 words on the ANSWER SHEET. Do not use your own name in the email; use “Li Ming” instead. (10 points)",
    "promptKind": "email",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2021,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2021,
      "sourceFileName": "2021年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "219b5815423f67b91f4ca743c52a271d13ce12f32b9198e3ca828e95f14887c9",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "2dc106c158a75d966fc62a320743c1d06fa0a21faed26281afa22677e2581e78",
    "requiredContentPoints": [
      "make some suggestions about finding a job in China"
    ]
  },
  {
    "questionId": "postgrad-en1-2021-writing-b",
    "promptText": "Write an essay of 160–200 words based on the picture below. In your essay, you should\n\n1) describe the picture briefly,\n2) interpret the implied meaning, and\n3) give your comments.",
    "directions": "Write your answer on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2021,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2021-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2021/postgrad-en1-2021-writing-b/prompt.png",
        "alt": "2021 年英语（一）写作题原卷图画",
        "fingerprint": "599873923ac540b3ef91364aa1d5efad84a06e588cd468f9708d095cbd66a8df"
      }
    ],
    "source": {
      "sourceYear": 2021,
      "sourceFileName": "2021年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "219b5815423f67b91f4ca743c52a271d13ce12f32b9198e3ca828e95f14887c9",
      "sourceAssetFingerprint": "599873923ac540b3ef91364aa1d5efad84a06e588cd468f9708d095cbd66a8df"
    },
    "fingerprint": "80f3edd3d638ba35ba85638436226d4bd2df3a75e7b5569aa1a843fc4ce679c8",
    "requiredContentPoints": [
      "describe the picture briefly",
      "interpret the implied meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2020-writing-a",
    "promptText": "The student union of your university has assigned you to inform the international students about an upcoming singing contest. Write a notice in about 100 words.",
    "directions": "Write your answer on the ANSWER SHEET. Do not use your own name in the notice. (10 points)",
    "promptKind": "notice",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2020,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2020,
      "sourceFileName": "2020年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "c555a320e417b3276c8e561463ef24ec8698bf52de58629462c9a13b3f87b31b",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "afb608f87d74a862875758c4d549eca9b5233343c1ed65e7aa989848b2dd52b9",
    "requiredContentPoints": [
      "inform the international students about an upcoming singing contest"
    ]
  },
  {
    "questionId": "postgrad-en1-2020-writing-b",
    "promptText": "Write an essay of 160–200 words based on the pictures below. In your essay, you should\n\n1) describe the pictures briefly,\n2) interpret the implied meaning, and\n3) give your comments.",
    "directions": "Write your answer on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2020,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2020-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2020/postgrad-en1-2020-writing-b/prompt.png",
        "alt": "2020 年英语（一）写作题原卷图画",
        "fingerprint": "6ccefc8e93a4fcd6bbfbdf996b5877fe078020d8e807c907b6964c6640bcbe1f"
      }
    ],
    "source": {
      "sourceYear": 2020,
      "sourceFileName": "2020年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "c555a320e417b3276c8e561463ef24ec8698bf52de58629462c9a13b3f87b31b",
      "sourceAssetFingerprint": "6ccefc8e93a4fcd6bbfbdf996b5877fe078020d8e807c907b6964c6640bcbe1f"
    },
    "fingerprint": "a50e933f28ac50b46c7e6e2178fedc06ef7885a6ff279a92bf458d0b43cdd7b5",
    "requiredContentPoints": [
      "describe the pictures briefly",
      "interpret the implied meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2019-writing-a",
    "promptText": "Suppose you are working for the “Aiding Rural Primary Schools” project of your university. Write an email to answer the inquiry from an international student volunteer, specifying the details of the project.",
    "directions": "You should write about 100 words on the ANSWER SHEET. Do not use your own name in the email; use “Li Ming” instead. (10 points)",
    "promptKind": "email",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2019,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2019,
      "sourceFileName": "2019年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "8f1589a4e2423615c04ef967866c5a87604024546be56bdafa5791abb28ecf61",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "9aac8e5b0ce4d1bb9b112a148af17240ccfbe104f219389015ef2740e290bf45",
    "requiredContentPoints": [
      "answer the inquiry from an international student volunteer",
      "specify the details of the project"
    ]
  },
  {
    "questionId": "postgrad-en1-2019-writing-b",
    "promptText": "Write an essay of 160–200 words based on the picture below. In your essay, you should\n\n1) describe the picture briefly,\n2) interpret the implied meaning, and\n3) give your comments.",
    "directions": "Write your answer on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2019,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2019-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2019/postgrad-en1-2019-writing-b/prompt.png",
        "alt": "2019 年英语（一）写作题原卷图画",
        "fingerprint": "26f0042669420be7de2ae7c38c66949f630e3bd08bcfef2b5d11f80f374fba73"
      }
    ],
    "source": {
      "sourceYear": 2019,
      "sourceFileName": "2019年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "8f1589a4e2423615c04ef967866c5a87604024546be56bdafa5791abb28ecf61",
      "sourceAssetFingerprint": "26f0042669420be7de2ae7c38c66949f630e3bd08bcfef2b5d11f80f374fba73"
    },
    "fingerprint": "d65c10d7136ac14de5913e1889df4f9bcc84a7044ad9ae7ba504a046e177be2f",
    "requiredContentPoints": [
      "describe the picture briefly",
      "interpret the implied meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2018-writing-a",
    "promptText": "Write an email to all international experts on campus, inviting them to attend the graduation ceremony. In your email, you should include time, place and other relevant information about the ceremony.",
    "directions": "You should write about 100 words neatly on the ANSWER SHEET. Do not use your own name at the end of the email. Use “Li Ming” instead. (10 points)",
    "promptKind": "email",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2018,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2018,
      "sourceFileName": "2018年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "30c5770f98ad41069a359692b1b9cb6bedb814f01ce60aaaec7c2629e055e27f",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "6bc753a2e8cfb38ebf4bc233fef2c80b813636e085e17a6e3b1b8c51a118f379",
    "requiredContentPoints": [
      "invite them to attend the graduation ceremony",
      "include time, place and other relevant information about the ceremony"
    ]
  },
  {
    "questionId": "postgrad-en1-2018-writing-b",
    "promptText": "Write an essay of 160–200 words based on the picture below. In your essay, you should\n\n1) describe the picture briefly,\n2) interpret the meaning, and\n3) give your comments.",
    "directions": "You should write neatly on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2018,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2018-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2018/postgrad-en1-2018-writing-b/prompt.png",
        "alt": "2018 年英语（一）写作题原卷图画",
        "fingerprint": "977d3eed7dad43269d9ea2070b8276aef2ac363e45768479db9669912fff9851"
      }
    ],
    "source": {
      "sourceYear": 2018,
      "sourceFileName": "2018年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "30c5770f98ad41069a359692b1b9cb6bedb814f01ce60aaaec7c2629e055e27f",
      "sourceAssetFingerprint": "977d3eed7dad43269d9ea2070b8276aef2ac363e45768479db9669912fff9851"
    },
    "fingerprint": "0f09a08c6512dbf88b29869e4b882260fbfa463bd187905f06b0f3b9f48d3ef0",
    "requiredContentPoints": [
      "describe the picture briefly",
      "interpret the meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2017-writing-a",
    "promptText": "You are to write an email to James Cook, a newly-arrived Australian professor, recommending some tourist attractions in your city. Please give reasons for your recommendation.",
    "directions": "You should write neatly on the ANSWER SHEET. Do not sign your own name at the end of the email. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "email",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2017,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2017,
      "sourceFileName": "2017年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "1cb61f5f3c978d7541d322efbc7294aefa8a7a3863452e3867b48077469ea78f",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "a8ab81ac31782890746bd7d4afe1896811c8e5dc84b41ef603391ac77f3d3729",
    "requiredContentPoints": [
      "recommend some tourist attractions in your city",
      "give reasons for your recommendation"
    ]
  },
  {
    "questionId": "postgrad-en1-2017-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following pictures. In your essay, you should\n\n1) describe the pictures briefly,\n2) interpret the meaning, and\n3) give your comments.",
    "directions": "You should write neatly on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2017,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2017-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2017/postgrad-en1-2017-writing-b/prompt.png",
        "alt": "2017 年英语（一）写作题原卷图画",
        "fingerprint": "797f38decf47e7aa292b2b0799c9fb0b2384920e7411570a3cd3217a01475bd0"
      }
    ],
    "source": {
      "sourceYear": 2017,
      "sourceFileName": "2017年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "1cb61f5f3c978d7541d322efbc7294aefa8a7a3863452e3867b48077469ea78f",
      "sourceAssetFingerprint": "797f38decf47e7aa292b2b0799c9fb0b2384920e7411570a3cd3217a01475bd0"
    },
    "fingerprint": "a1b1ad70459667842f3730be06b918db405f527265eb62f43d149a93e8939b8d",
    "requiredContentPoints": [
      "describe the pictures briefly",
      "interpret the meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2016-writing-a",
    "promptText": "Suppose you are a librarian in your university. Write a notice of about 100 words, providing the newly-enrolled international students with relevant information about the library.",
    "directions": "You should write neatly on the ANSWER SHEET. Do not sign your own name at the end of the notice. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "notice",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2016,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2016,
      "sourceFileName": "2016年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "f8d18488cba195df79abcb7cd4e4aab89486746fe641d9c0e6d74f24cc6261ee",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "21d3bedf26971705f82888cf5fd7fa33fcc3a421cbc3cef4e3e4e4cc17925c2e",
    "requiredContentPoints": [
      "provide the newly-enrolled international students with relevant information about the library"
    ]
  },
  {
    "questionId": "postgrad-en1-2016-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following pictures. In your essay, you should\n\n1) describe the pictures briefly,\n2) interpret the meaning, and\n3) give your comments.",
    "directions": "You should write neatly on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2016,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2016-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2016/postgrad-en1-2016-writing-b/prompt.png",
        "alt": "2016 年英语（一）写作题原卷图画",
        "fingerprint": "769376b3aa112d2342d09b2deab23268feecf169e79a9e18339e661d6f76d94a"
      }
    ],
    "source": {
      "sourceYear": 2016,
      "sourceFileName": "2016年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "f8d18488cba195df79abcb7cd4e4aab89486746fe641d9c0e6d74f24cc6261ee",
      "sourceAssetFingerprint": "769376b3aa112d2342d09b2deab23268feecf169e79a9e18339e661d6f76d94a"
    },
    "fingerprint": "3b3785b5a3caf22809641d2447c7ad62d1b6d466c37bf84ebb32ff21ae4e2678",
    "requiredContentPoints": [
      "describe the pictures briefly",
      "interpret the meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2015-writing-a",
    "promptText": "You are going to host a club reading session. Write an email of about 100 words recommending a book to the club members.\n\nYou should state reasons for your recommendation.",
    "directions": "You should write neatly on the ANSWER SHEET. Do not sign your own name at the end of the letter. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "email",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2015,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2015,
      "sourceFileName": "2015年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "a93cd343694ab930e49c0eadb28e685c1b2efc7f1c6f57b50826ba23c2876dce",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "00289bded375d47ce10ac89209400b06bd5db8f95aa0540225ad5246b3a95b6f",
    "requiredContentPoints": [
      "recommend a book to the club members",
      "state reasons for your recommendation"
    ]
  },
  {
    "questionId": "postgrad-en1-2015-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following picture. In your essay, you should\n\n1) describe the picture briefly,\n2) interpret its intended meaning, and\n3) give your comments.",
    "directions": "You should write neatly on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2015,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2015-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2015/postgrad-en1-2015-writing-b/prompt.png",
        "alt": "2015 年英语（一）写作题原卷图画",
        "fingerprint": "faa6e22f346bf84214f65a06f5120e6bb70e37c29ce1cf9ba7e5fd7e5f6910a6"
      }
    ],
    "source": {
      "sourceYear": 2015,
      "sourceFileName": "2015年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "a93cd343694ab930e49c0eadb28e685c1b2efc7f1c6f57b50826ba23c2876dce",
      "sourceAssetFingerprint": "faa6e22f346bf84214f65a06f5120e6bb70e37c29ce1cf9ba7e5fd7e5f6910a6"
    },
    "fingerprint": "383fc0a5330dbf7b1de4778778bf1ced90d402a52b92399004979c2a34268dc5",
    "requiredContentPoints": [
      "describe the picture briefly",
      "interpret its intended meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2014-writing-a",
    "promptText": "Write a letter of about 100 words to the president of your university, suggesting how to improve students’ physical condition.\n\nYou should include the details you think necessary.",
    "directions": "You should write neatly on the ANSWER SHEET. Do not sign your own name at the end of the letter. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "letter",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2014,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2014,
      "sourceFileName": "2014年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "3d576ac3c9128eb7952cea9ec128f61447b15c04fecdb36c766ebe99b23bddab",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "e6be3fc38282b43bb3e0a5dd781231abe26b72f4c175271ce074c3d3eb8ef6ea",
    "requiredContentPoints": [
      "suggest how to improve students’ physical condition",
      "include the details you think necessary"
    ]
  },
  {
    "questionId": "postgrad-en1-2014-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following drawing. In your essay, you should\n\n1) describe the drawing briefly,\n2) interpret its intended meaning, and\n3) give your comments.",
    "directions": "You should write neatly on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2014,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2014-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2014/postgrad-en1-2014-writing-b/prompt.png",
        "alt": "2014 年英语（一）写作题原卷图画",
        "fingerprint": "541a8c3af468a672c1e18d1d2289b1aab3fd63aa71aca170a41a1c22b216ff8a"
      }
    ],
    "source": {
      "sourceYear": 2014,
      "sourceFileName": "2014年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "3d576ac3c9128eb7952cea9ec128f61447b15c04fecdb36c766ebe99b23bddab",
      "sourceAssetFingerprint": "541a8c3af468a672c1e18d1d2289b1aab3fd63aa71aca170a41a1c22b216ff8a"
    },
    "fingerprint": "18310501bb811f52c834e40fb55b3b5eda3d4b66ebd536157c7fd66149c958de",
    "requiredContentPoints": [
      "describe the drawing briefly",
      "interpret its intended meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2013-writing-a",
    "promptText": "Write an e-mail of about 100 words to a foreign teacher in your college, inviting him/her to be a judge for the upcoming English speech contest.\n\nYou should include the details you think necessary.",
    "directions": "You should write neatly on the ANSWER SHEET. Do not sign your own name at the end of the e-mail. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "email",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2013,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2013,
      "sourceFileName": "2013年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "35528e5ac06998f252296b29bffbfd1dc6575f1c8e494f2fd1f5b460a9bef501",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "f36bc6fe6d5bf393a8e61135cd780f8eab2e8794ed12be237f27ce5a8265891a",
    "requiredContentPoints": [
      "invite him/her to be a judge for the upcoming English speech contest",
      "include the details you think necessary"
    ]
  },
  {
    "questionId": "postgrad-en1-2013-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following drawing. In your essay, you should\n\n1) describe the drawing briefly,\n2) interpret its intended meaning, and\n3) give your comments.",
    "directions": "You should write neatly on the ANSWER SHEET. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2013,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2013-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2013/postgrad-en1-2013-writing-b/prompt.png",
        "alt": "2013 年英语（一）写作题原卷图画",
        "fingerprint": "42186683e3063edcc2eb710f5c7ce3949886623039a60f39cad76915d0f58d38"
      }
    ],
    "source": {
      "sourceYear": 2013,
      "sourceFileName": "2013年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "35528e5ac06998f252296b29bffbfd1dc6575f1c8e494f2fd1f5b460a9bef501",
      "sourceAssetFingerprint": "42186683e3063edcc2eb710f5c7ce3949886623039a60f39cad76915d0f58d38"
    },
    "fingerprint": "1216859f751400ef383f31dae5bd1b76acf0462b73b637e2ac110480626a5e06",
    "requiredContentPoints": [
      "describe the drawing briefly",
      "interpret its intended meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2012-writing-a",
    "promptText": "Some international students are coming to your university. Write them an email in the name of the Students’ Union to\n\n1) extend your welcome and\n2) provide some suggestions for their campus life here.",
    "directions": "You should write about 100 words on ANSWER SHEET 2. Do not sign your own name at the end of the letter. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "email",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2012,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2012,
      "sourceFileName": "2012年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "8ba9d02a72a143b538a52487065b05d82cfabd13e170f9f6d432fa96272a52e8",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "0915e79468bee8adaccba72a072d1bac734f753a4ee7fb15dd1e74737345e339",
    "requiredContentPoints": [
      "extend your welcome",
      "provide some suggestions for their campus life here"
    ]
  },
  {
    "questionId": "postgrad-en1-2012-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following drawing. In your essay you should\n\n1) describe the drawing briefly,\n2) explain its intended meaning, and\n3) give your comments.",
    "directions": "You should write neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2012,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2012-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2012/postgrad-en1-2012-writing-b/prompt.png",
        "alt": "2012 年英语（一）写作题原卷图画",
        "fingerprint": "6db3ad192a455b09e4522c731826e80aa2d583d4656c3b269a767154c14c6f64"
      }
    ],
    "source": {
      "sourceYear": 2012,
      "sourceFileName": "2012年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "8ba9d02a72a143b538a52487065b05d82cfabd13e170f9f6d432fa96272a52e8",
      "sourceAssetFingerprint": "6db3ad192a455b09e4522c731826e80aa2d583d4656c3b269a767154c14c6f64"
    },
    "fingerprint": "c6737f12aec281048f732a503b8bac42f0ed9cd6e0d79c853df59648525519f5",
    "requiredContentPoints": [
      "describe the drawing briefly",
      "explain its intended meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2011-writing-a",
    "promptText": "Write a letter to a friend of yours to\n\n1) recommend one of your favorite movies and\n2) give reasons for your recommendation.",
    "directions": "You should write about 100 words on ANSWER SHEET 2. Do not sign your own name at the end of the letter. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "letter",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2011,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2011,
      "sourceFileName": "2011年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "020f91d3db7ba5b489674b2615b56e58daa1f42762a4267a7369a67e8580af70",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "13fe2744468b394ed83074ca33a01fdd8c8a3d546043888cdcb7e630bc047dc1",
    "requiredContentPoints": [
      "recommend one of your favorite movies",
      "give reasons for your recommendation"
    ]
  },
  {
    "questionId": "postgrad-en1-2011-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following drawing. In your essay, you should\n\n1) describe the drawing briefly,\n2) explain its intended meaning, and\n3) give your comments.",
    "directions": "You should write neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2011,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2011-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2011/postgrad-en1-2011-writing-b/prompt.png",
        "alt": "2011 年英语（一）写作题原卷图画",
        "fingerprint": "277bfcf64b3dae1106e2a9e03afb52a5311ad99b49615f252d1778fff940c77e"
      }
    ],
    "source": {
      "sourceYear": 2011,
      "sourceFileName": "2011年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "020f91d3db7ba5b489674b2615b56e58daa1f42762a4267a7369a67e8580af70",
      "sourceAssetFingerprint": "277bfcf64b3dae1106e2a9e03afb52a5311ad99b49615f252d1778fff940c77e"
    },
    "fingerprint": "6676cad2bd3708119a8af4c533e7d8ec18aacfe77b1afea2f643a5b2c58e734b",
    "requiredContentPoints": [
      "describe the drawing briefly",
      "explain its intended meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2010-writing-a",
    "promptText": "You are supposed to write for the Postgraduates’ Association a notice to recruit volunteers for an international conference on globalization. The notice should include the basic qualifications for applicants and other information which you think is relevant.",
    "directions": "You should write about 100 words on ANSWER SHEET 2. Do not sign your own name at the end of the notice. Use “Postgraduates’ Association” instead. (10 points)",
    "promptKind": "notice",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2010,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2010,
      "sourceFileName": "2010年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "e69a149ff7cb2d6303521dfcf68a6d5bedef5cc6056df9b92836ea2352a19bc1",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "6c06373f67cf617ce05000c4f9b72a1d5f0522e0c9b58870b4d04f52bc8ec5ff",
    "requiredContentPoints": [
      "include the basic qualifications for applicants",
      "include other information which you think is relevant"
    ]
  },
  {
    "questionId": "postgrad-en1-2010-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following drawing. In your essay, you should\n\n1) describe the drawing briefly,\n2) explain its intended meaning, and\n3) give your comments.",
    "directions": "You should write neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2010,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2010-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2010/postgrad-en1-2010-writing-b/prompt.png",
        "alt": "2010 年英语（一）写作题原卷图画",
        "fingerprint": "cd7c45352a175837e0411f804f4a8c5b7128964afb25901efd6ee5f9773efefa"
      }
    ],
    "source": {
      "sourceYear": 2010,
      "sourceFileName": "2010年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "e69a149ff7cb2d6303521dfcf68a6d5bedef5cc6056df9b92836ea2352a19bc1",
      "sourceAssetFingerprint": "cd7c45352a175837e0411f804f4a8c5b7128964afb25901efd6ee5f9773efefa"
    },
    "fingerprint": "6027036262f5311f6fbf64d5d59050b5de237d9252826d2465ade08af2e30af1",
    "requiredContentPoints": [
      "describe the drawing briefly",
      "explain its intended meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2009-writing-a",
    "promptText": "Restrictions on the use of plastic bags have not been so successful in some regions. “White Pollution” is still going on.\n\nWrite a letter to the editor(s) of your local newspaper to\n\n1) give your opinions briefly, and\n2) make two or three suggestions.",
    "directions": "You should write about 100 words on ANSWER SHEET 2. Do not sign your own name at the end of the letter. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "letter",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2009,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2009,
      "sourceFileName": "2009年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "6a4003eb037362e5fff38612ff5b258459479ae32b1a666b881a6e0f2025eef0",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "92f6a00e59c2c7add5ac07e87f85739cb0732f18162eeb0eb095a82da0483b87",
    "requiredContentPoints": [
      "give your opinions briefly",
      "make two or three suggestions"
    ]
  },
  {
    "questionId": "postgrad-en1-2009-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following drawing. In your essay, you should\n\n1) describe the drawing briefly,\n2) explain its intended meaning, and then\n3) give your comments.",
    "directions": "You should write neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2009,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2009-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2009/postgrad-en1-2009-writing-b/prompt.png",
        "alt": "2009 年英语（一）写作题原卷图画",
        "fingerprint": "005f3299c78d311718e7c59b911624b4116f5c7df186159023a726a434006cca"
      }
    ],
    "source": {
      "sourceYear": 2009,
      "sourceFileName": "2009年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "6a4003eb037362e5fff38612ff5b258459479ae32b1a666b881a6e0f2025eef0",
      "sourceAssetFingerprint": "005f3299c78d311718e7c59b911624b4116f5c7df186159023a726a434006cca"
    },
    "fingerprint": "46aaaa6cfc4254dc96cf44ea3628a647d00b92d74455b686e9f6a0378c761aed",
    "requiredContentPoints": [
      "describe the drawing briefly",
      "explain its intended meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2008-writing-a",
    "promptText": "You have just come back from Canada and found a music CD in your luggage that you forgot to return to Bob, your landlord there. Write him a letter to\n\n1) make an apology, and\n2) suggest a solution.",
    "directions": "You should write about 100 words on ANSWER SHEET 2. Do not sign your own name at the end of the letter. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "letter",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2008,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2008,
      "sourceFileName": "2008年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "bb1690e939c18790fee13883337f24e34df793ae4b9e5579ae0f4b4a2a242cf9",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "81c12085b959c91ee1cda9b44a769a966d26e1cb4649a6da388d9c17fc46d2c5",
    "requiredContentPoints": [
      "make an apology",
      "suggest a solution"
    ]
  },
  {
    "questionId": "postgrad-en1-2008-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following drawing. In your essay, you should\n\n1) describe the drawing briefly,\n2) explain its intended meaning, and then\n3) give your comments.",
    "directions": "You should write neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2008,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2008-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2008/postgrad-en1-2008-writing-b/prompt.png",
        "alt": "2008 年英语（一）写作题原卷图画",
        "fingerprint": "957be43f4ea5ec17305f42123e48358b00c19a140dd319a07c3fa0195c8efc45"
      }
    ],
    "source": {
      "sourceYear": 2008,
      "sourceFileName": "2008年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "bb1690e939c18790fee13883337f24e34df793ae4b9e5579ae0f4b4a2a242cf9",
      "sourceAssetFingerprint": "957be43f4ea5ec17305f42123e48358b00c19a140dd319a07c3fa0195c8efc45"
    },
    "fingerprint": "3dc818d5c69068bc660f0048100bf1ceb68efe81cbf273ae67981474586f756f",
    "requiredContentPoints": [
      "describe the drawing briefly",
      "explain its intended meaning",
      "give your comments"
    ]
  },
  {
    "questionId": "postgrad-en1-2007-writing-a",
    "promptText": "Write a letter to your university library, making suggestions for improving its service.",
    "directions": "You should write about 100 words on ANSWER SHEET 2. Do not sign your own name at the end of the letter. Use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "letter",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2007,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2007,
      "sourceFileName": "2007年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "3fad387e58419f379bed9f6d501c213c3f05cef762b1d1777e3e1dda346414a1",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "6c8098fd53e606b85c07839a6c3ee87280c2ecd674dcdaaf11e5161467d6a918",
    "requiredContentPoints": [
      "make suggestions for improving its service"
    ]
  },
  {
    "questionId": "postgrad-en1-2007-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following drawing. In your essay, you should\n\n1) describe the drawing briefly,\n2) explain its intended meaning, and then\n3) support your view with an example/examples.",
    "directions": "You should write neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2007,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2007-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2007/postgrad-en1-2007-writing-b/prompt.png",
        "alt": "2007 年英语（一）写作题原卷图画",
        "fingerprint": "f81509b12e2106bcdfd6779822be7472739bbfeec4706bc5f9e62e8b01b7e9b1"
      }
    ],
    "source": {
      "sourceYear": 2007,
      "sourceFileName": "2007年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "3fad387e58419f379bed9f6d501c213c3f05cef762b1d1777e3e1dda346414a1",
      "sourceAssetFingerprint": "f81509b12e2106bcdfd6779822be7472739bbfeec4706bc5f9e62e8b01b7e9b1"
    },
    "fingerprint": "cb8831680e94a155e6e1724df693b4621c8eb7ab5823cd09cfbcfde33458a517",
    "requiredContentPoints": [
      "describe the drawing briefly",
      "explain its intended meaning",
      "support your view with an example/examples"
    ]
  },
  {
    "questionId": "postgrad-en1-2006-writing-a",
    "promptText": "You want to contribute to Project Hope by offering financial aid to a child in a remote area. Write a letter to the department concerned, asking them to help find a candidate. You should specify what kind of child you want to help and how you will carry out your plan.",
    "directions": "Write your letter in no less than 100 words. Write it neatly on ANSWER SHEET 2. Do not sign your own name at the end of the letter; use “Li Ming” instead. Do not write the address. (10 points)",
    "promptKind": "letter",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2006,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2006,
      "sourceFileName": "2006年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "fa6ca5315c526d0c15ad35afb504b7dbc30a0ba8150be4d8fde23529886dc1dd",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "d80e012092facb8e8cb6a6a9c487b3be5c16f73c5ab90e19e58c8ee4664c3af2",
    "requiredContentPoints": [
      "specify what kind of child you want to help",
      "specify how you will carry out your plan"
    ]
  },
  {
    "questionId": "postgrad-en1-2006-writing-b",
    "promptText": "Study the following photos carefully and write an essay in which you should\n\n1) describe the photos briefly,\n2) interpret the social phenomenon reflected by them, and\n3) give your point of view.",
    "directions": "You should write 160–200 words neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2006,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2006-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2006/postgrad-en1-2006-writing-b/prompt.png",
        "alt": "2006 年英语（一）写作题原卷图画",
        "fingerprint": "b37261e18489813e12298b182c167992a6829898424e2661341d8df20f1e2015"
      }
    ],
    "source": {
      "sourceYear": 2006,
      "sourceFileName": "2006年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "fa6ca5315c526d0c15ad35afb504b7dbc30a0ba8150be4d8fde23529886dc1dd",
      "sourceAssetFingerprint": "b37261e18489813e12298b182c167992a6829898424e2661341d8df20f1e2015"
    },
    "fingerprint": "baeb4987857a1ed9778ff953992848b0b08c5194fea2b6b3138d901a73d1f111",
    "requiredContentPoints": [
      "describe the photos briefly",
      "interpret the social phenomenon reflected by them",
      "give your point of view"
    ]
  },
  {
    "questionId": "postgrad-en1-2005-writing-a",
    "promptText": "Two months ago you got a job as an editor for the magazine Designs & Fashions. But now you find that the work is not what you expected. You decide to quit. Write a letter to your boss, Mr. Wang, telling him your decision, stating your reason(s), and making an apology.",
    "directions": "Write your letter with no less than 100 words. Write it neatly on ANSWER SHEET 2. Do not sign your own name at the end of the letter; use “Li Ming” instead. You do not need to write the address. (10 points)",
    "promptKind": "letter",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-a",
    "year": 2005,
    "maxScore": 10,
    "targetWordRange": {
      "min": 90,
      "max": 110
    },
    "assets": [],
    "source": {
      "sourceYear": 2005,
      "sourceFileName": "2005年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part A",
      "sourceQuestionNumber": 51,
      "sourceFingerprint": "d5f1078e6349f7a704118e835967fca1419559737cf4c3ae138ac5f6560305ad",
      "sourceAssetFingerprint": null
    },
    "fingerprint": "bd1927fb3f3a1ae0105e3040fd6e588f5a9a8b4856afa136ddef8b422731f5c1",
    "requiredContentPoints": [
      "telling him your decision",
      "stating your reason(s)",
      "making an apology"
    ]
  },
  {
    "questionId": "postgrad-en1-2005-writing-b",
    "promptText": "Write an essay of 160–200 words based on the following drawing. In your essay, you should first describe the drawing, then interpret its meaning, and give your comment on it.",
    "directions": "You should write neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2005,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2005-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2005/postgrad-en1-2005-writing-b/prompt.png",
        "alt": "2005 年英语（一）写作题原卷图画",
        "fingerprint": "de3051cd99aa1856afbc89b7b9d2379374708755239b86e7d9ffc886046f20ef"
      }
    ],
    "source": {
      "sourceYear": 2005,
      "sourceFileName": "2005年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing, Part B",
      "sourceQuestionNumber": 52,
      "sourceFingerprint": "d5f1078e6349f7a704118e835967fca1419559737cf4c3ae138ac5f6560305ad",
      "sourceAssetFingerprint": "de3051cd99aa1856afbc89b7b9d2379374708755239b86e7d9ffc886046f20ef"
    },
    "fingerprint": "f3ea52ccd4a60294aa9f87e971e85bebf71a0b0d706f8e071a6ce175b09cb560",
    "requiredContentPoints": [
      "describe the drawing",
      "interpret its meaning",
      "give your comment on it"
    ]
  },
  {
    "questionId": "postgrad-en1-2004-writing-b",
    "promptText": "Study the following drawing carefully and write an essay in which you should\n\n1) describe the drawing,\n2) interpret its meaning, and\n3) support your view with examples.",
    "directions": "You should write about 200 words neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2004,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2004-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2004/postgrad-en1-2004-writing-b/prompt.png",
        "alt": "2004 年英语（一）写作题原卷图画",
        "fingerprint": "2c6b053260d0dacbe67967c8da175499da653e468df03babe193989d42525880"
      }
    ],
    "source": {
      "sourceYear": 2004,
      "sourceFileName": "2004年真题及答案速查.pdf",
      "sourcePage": 14,
      "sourceSection": "Section III Writing",
      "sourceQuestionNumber": 46,
      "sourceFingerprint": "36010d0225fabc9c0fa43c2a2c623d39440faef05ddf993e58e87c7dcab1f901",
      "sourceAssetFingerprint": "2c6b053260d0dacbe67967c8da175499da653e468df03babe193989d42525880"
    },
    "fingerprint": "162f8f310060299e71b8f91be2b414ac91055f5c4cdf50a00dca50f5d7787818",
    "requiredContentPoints": [
      "describe the drawing",
      "interpret its meaning",
      "support your view with examples"
    ]
  },
  {
    "questionId": "postgrad-en1-2003-writing-b",
    "promptText": "Study the following set of drawings carefully and write an essay in which you should\n\n1) describe the set of drawings, interpret its meaning, and\n2) point out its implications in our life.",
    "directions": "You should write about 200 words neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2003,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2003-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2003/postgrad-en1-2003-writing-b/prompt.png",
        "alt": "2003 年英语（一）写作题原卷图画",
        "fingerprint": "87a9f715e0d0f032af2c6144eb31b4f0168c8aa124a9769d0fc60968b9853371"
      }
    ],
    "source": {
      "sourceYear": 2003,
      "sourceFileName": "2003年真题及答案速查.pdf",
      "sourcePage": 15,
      "sourceSection": "Section III Writing",
      "sourceQuestionNumber": 46,
      "sourceFingerprint": "7f91d59c3e0985748472ec0c38a0c53b016df13c20e74ab7b4c8d161d27666b5",
      "sourceAssetFingerprint": "87a9f715e0d0f032af2c6144eb31b4f0168c8aa124a9769d0fc60968b9853371"
    },
    "fingerprint": "9a13651c150242011f64395f4250485157c3f8c8891d9ca7c57e4e2691d50ddc",
    "requiredContentPoints": [
      "describe the set of drawings, interpret its meaning",
      "point out its implications in our life"
    ]
  },
  {
    "questionId": "postgrad-en1-2002-writing-b",
    "promptText": "Study the following picture carefully and write an essay entitled “Cultures—National and International”.\n\nIn the essay you should\n\n1) describe the picture and interpret its meaning, and\n2) give your comment on the phenomenon.",
    "directions": "You should write about 200 words neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2002,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2002-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2002/postgrad-en1-2002-writing-b/prompt.png",
        "alt": "2002 年英语（一）写作题原卷图画",
        "fingerprint": "9271d3705b9f5d1c0789954d723564117cd7f201a5a28104a5dc03323b79f590"
      }
    ],
    "source": {
      "sourceYear": 2002,
      "sourceFileName": "2002年真题及答案速查.pdf",
      "sourcePage": 14,
      "sourceSection": "Section III Writing",
      "sourceQuestionNumber": 46,
      "sourceFingerprint": "daadfa9ba2fc439b7b8d0314b76f1f279cbd97c53716ec1324ba01ba631854cb",
      "sourceAssetFingerprint": "9271d3705b9f5d1c0789954d723564117cd7f201a5a28104a5dc03323b79f590"
    },
    "fingerprint": "b856a773606226fcc774d7add16ead2656f6db48a147a8614ca1b04b430c3e70",
    "requiredContentPoints": [
      "describe the picture and interpret its meaning",
      "give your comment on the phenomenon"
    ]
  },
  {
    "questionId": "postgrad-en1-2001-writing-b",
    "promptText": "Among all the worthy feelings of mankind, love is probably the noblest, but everyone has his/her own understanding of it.\n\nThere has been a discussion recently on the issue in a newspaper. Write an essay to the newspaper to\n\n1) show your understanding of the symbolic meaning of the picture below,\n2) give a specific example, and\n3) give your suggestion as to the best way to show love.",
    "directions": "You should write about 200 words neatly on ANSWER SHEET 2. (20 points)",
    "promptKind": "picture",
    "sourceType": "official",
    "taskType": "postgrad-en1-writing-b",
    "year": 2001,
    "maxScore": 20,
    "targetWordRange": {
      "min": 160,
      "max": 200
    },
    "assets": [
      {
        "assetId": "postgrad-en1-2001-writing-b-prompt",
        "kind": "source_picture",
        "src": "/writing/questions/2001/postgrad-en1-2001-writing-b/prompt.png",
        "alt": "2001 年英语（一）写作题原卷图画",
        "fingerprint": "6ac148af5b85eced24cd15cb3d4608cc53ccb61bc363df7ccdb6549905ed8ee7"
      }
    ],
    "source": {
      "sourceYear": 2001,
      "sourceFileName": "2001年真题及答案速查.pdf",
      "sourcePage": 16,
      "sourceSection": "Section III Writing",
      "sourceQuestionNumber": 46,
      "sourceFingerprint": "6a7ce48de4db5100520a73ea99633654debc49dde01cff310331e6c464d44892",
      "sourceAssetFingerprint": "6ac148af5b85eced24cd15cb3d4608cc53ccb61bc363df7ccdb6549905ed8ee7"
    },
    "fingerprint": "2e5cbb992f0ccc39be2700d3758eef53de928b3e9fc2ee8c5cfffcdaf28db378",
    "requiredContentPoints": [
      "show your understanding of the symbolic meaning of the picture below",
      "give a specific example",
      "give your suggestion as to the best way to show love"
    ]
  }
];
